services:
  price-pusher:
    # Use this to build the price pusher from source. A dependency of the pusher docker
    # image is the pyth-crosschain monorepo lerna docker image. Build lerna image
    # using the following command from the repo root:
    # `docker buildx build -f Dockerfile.lerna -t lerna .`
    #
    # Please note that the docker build from source only works in x86_64 platforms
    # and doesn't work on arm platforms (like Apple M1/M2).
    #
    # build:
    #   context: .

    # Replace <version> with the latest released image of the price pusher from here:
    # https://gallery.ecr.aws/pyth-network/xc-price-pusher
    image: public.ecr.aws/pyth-network/xc-price-pusher:v<version>
    restart: always
    command:
      - "--"
      - "evm"
      - "--endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://virtual.mode.rpc.tenderly.co/bc9276a3-5543-4510-8e6f-4546318b368c"
      - "--mnemonic-file"
      - "/mnemonic"
      # Replace this with the address of the Pyth contract on the EVM network.
      - "--pyth-contract-address"
      - "0xA2aa501b19aff244D90cc15a4Cf739D2725B5729"
      - "--price-service-endpoint"
      - "https://hermes.pyth.network" # Replace this with a private Hermes RPC for more reliability
      - "--price-config-file"
      - "/price_config"
    configs:
      - mnemonic
      - price_config
configs:
  mnemonic:
    file: ./mnemonic.txt # Replace this with the path to the mnemonic file
  price_config:
    file: ./price-config.yaml # Replace this with the path to the price configuration file
